services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ruka
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asito_development
    volumes:
      - ruka_postgres_data:/var/lib/postgresql/data

volumes:
  ruka_postgres_data:
